app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('', include('main.urls')),
  path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy, re_path

from . import views
from .views import ResetPasswordView

# from rest_framework import routers


app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("user_info/", views.user_info, name="user_info"),
    path("aspirant_info/", views.aspirant_info, name="aspirant_info"),
    path("competitions/", views.list_competitions, name="list_competitions"),
    path("competition/<int:id>", views.list_attendees, name="list_attendees"),
    path("competition_public/<int:id>", views.list_attendees_public, name="list_attendees_public"),
    path("edit_transportation_admin/<int:id>", views.edit_transportation_admin, name="edit_transportation_admin"),
    path("transportation_publish/<int:id>", views.transportation_publish, name="transportation_publish"),
    path("transportation_generate/<int:id>", views.transportation_generate, name="transportation_generate"),
    path("transportation_lock_toggle/<int:id>", views.transportation_lock_toggle, name="transportation_lock_toggle"),
    path("transportation_remove_driver/<int:id>", views.transportation_remove_driver, name="transportation_remove_driver"),
    path("transportation_remove_passenger/<int:registration_id>", views.transportation_remove_passenger, name="transportation_remove_passenger"),
    path("clear_transportation/<int:id>", views.clear_transportation, name="clear_transportation"),
    path("transportation_create_driver/<int:id>", views.transportation_create_driver, name="transportation_create_driver"),
    path("transportation_append_passenger/<int:transport_id>/<int:registration_id>", views.transportation_append_passenger, name="transportation_append_passenger"),
    path('set_available_seats/<int:transportation_id>/<int:seats>/', views.set_available_seats, name='set_available_seats'),
    path('update_note/<int:pk>/', views.update_note, name='update_note'),
    path("transportation_public/<int:id>", views.transportation_public, name="transportation_public"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("hr/", views.list_members, name="list_members"),
    path("aspirants/<int:person_id>", views.list_aspirants, name="list_aspirants"),
    path("aspirants/add", views.add_aspirant, name="add_aspirant"),
    path("aspirants/edit/<int:pk>", views.edit_aspirant, name="edit_aspirant"),
    path("aspirants/accept/<int:pk>", views.accept_aspirant, name="accept_aspirant"),
    path("aspirants/edit_note/<int:pk>", views.aspirant_update_note, name="aspirant_update_note"),
    path("medical_exams/", views.medical_exams, name="medical_exams"),
    path("medical_exam/verify/<int:exam_id>/", views.verify_exam, name="verify_exam"),
    path("medical_exams_all/", views.medical_exams_all, name="medical_exams_all"),
    path("medical_exams_history/<int:person_id>", views.medical_exams_history, name="medical_exams_history"),
    path("brigade/verify/<int:brigade_id>/", views.verify_brigade, name="verify_brigade"),
    path("treasurer/<int:season_year>", views.treasurer, name="treasurer"),
    path("sinners/<int:season_year>", views.sinners, name="sinners"),
    path("brigades/<int:season_year>", views.brigades, name="brigades"),
    path("brigade_requests/", views.brigade_requests, name="brigade_requests"),
    path("brigade_history/<int:person_id>", views.brigade_history, name="brigade_history"),
    path("add_brigade/", views.add_brigade, name="add_brigade"),
    path("register/", views.register, name="register"),
    path("register_to/<int:id>", views.register_to, name="register_to"),
    path("edit_registration/<int:registration_id>", views.edit_registration, name="edit_registration"),
    path("unregister/<int:id>", views.unregister, name="unregister"),
    path("upload_new_exam_file/", views.upload_examination, name="upload_exam_file"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/competitions', views.api_competitions, name='api_competitions'),
    path('api/registrations/<int:iscsps_id>', views.api_registrations, name='api_registrations'),
    path('api/examinations', views.api_examinations, name='api_examinations'),
    path('api/add_new_member_cus/<int:pk>', views.add_new_member_cus, name='add_new_member_cus'),
    path('api/list_new_members', views.list_new_members, name='list_new_members'),
    re_path(
        r'^payment_details/(?P<fee_type>[^/]+)/(?P<year>\d+)/(?P<amount>\d+)(?:/(?P<optional_text>[^/]+))?/$',
        views.payment_details, name='payment_details'),
    path("payment_history/<int:person_id>", views.payment_history, name='payment_history'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='main/users/password_reset_confirm.html',
                                                     success_url=reverse_lazy("main:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'),
         name='password_reset_complete'),
    # path to toggle copaid for each competition
    path('toggle_co_paid/<int:competition_id>/<int:pk>/', views.toggle_co_paid, name='toggle_co_paid'),
    path('toggle_aspirant_temp_registration/<int:person_id>/', views.toggle_aspirant_temp_registration, name='toggle_aspirant_temp_registration'),
    path('toggle_aspirant_big_registration/<int:person_id>/', views.toggle_aspirant_big_registration,
         name='toggle_aspirant_big_registration'),
    path('toggle_aspirant_small_registration/<int:person_id>/', views.toggle_aspirant_small_registration,
         name='toggle_aspirant_small_registration'),
    path('toggle_aspirant_gdpr/<int:person_id>/', views.toggle_aspirant_gdpr,
         name='toggle_aspirant_gdpr'),
    path('toggle_aspirant_information_agreed/<int:person_id>/', views.toggle_aspirant_information_agreed,
         name='toggle_aspirant_information_agreed'),
    path('toggle_aspirant_pictures2pcs/<int:person_id>/', views.toggle_aspirant_pictures2pcs,
         name='toggle_aspirant_pictures2pcs'),
    path('send_payment_email/<int:person_id>/', views.send_payment_email, name='send_payment_email'),
]

app/main/views.py
import csv
import json
import re
import ssl
import urllib
import io
from datetime import date, datetime, timedelta
from urllib.error import URLError
from urllib.request import urlopen

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.db.models import Max, Q, ExpressionWrapper, F, fields
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.http import require_POST

from .utils import update_user_medical_examination_on_IS, add_new_member_to_CSPS, add_new_member_to_CUS, \
    get_unfulfilled_lists, remove_atendee_from_transportation, apply_for_competition, delete_competition_application
from .forms import RegistrationForm, ExaminationForm, BrigadeForm, PaymentForm, MedicalExaminationRejectionForm, \
    AspirantForm
from .models import Competition, Person, MedicalExamination, Brigade, Payment, Registration, FulfilledMembership, \
    FulfilledBrigade, ChampionshipCourseRule, MemberStatus, Transport
from .utils import get_season_year


def is_treasurer(user):
    return user.groups.filter(name='Treasurer Role').exists()


def is_hr(user):
    return user.groups.filter(name='HR role').exists()


def is_competition_manager(user):
    return user.groups.filter(name='Competition Manager Role').exists()


def is_medic(user):
    return user.groups.filter(name='Medical Examination Role').exists()


def is_brigade_role(user):
    return user.groups.filter(name='Brigade Manager').exists()


def homepage(request):
    return render(request=request,
                  template_name="main/home.html",
                  context={"competitions": Competition.objects.all})


transports = (
    ("", _('---------')),  # default choice
    (0, _('Individual')),
    (1, _('I need a ride')),
    (2, _('I drive (1 spare pl.)')),
    (3, _('I drive (2 spare pl.)')),
    (4, _('I drive (3 spare pl.)')),
    (5, _('I drive (4 spare pl.)')),
    (6, _('I drive (5 spare pl.)')),
    (7, _('I drive (6 spare pl.)')),
)


@login_required
def update_membership_payments(person: Person, current_date: date, request=None):
    """
    BRIGADE:
    Given year, check payments between 1.7.YEAR-1 to 1.7.YEAR
    """
    person.update_fees(current_date, request)


@login_required
@user_passes_test(is_treasurer)
def treasurer(request, season_year):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        payment = form.save(commit=False)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = PaymentForm()

    # check, if FulfilledMembership has missing some people for season_year. If so, recreate them
    # Check Memberships
    mems = FulfilledMembership.objects.filter(year=season_year, person__user__is_active=True)
    people_in_mem = [a.person for a in mems]
    missing_people = set(Person.objects.filter(user__is_active=True)).difference(people_in_mem)
    for missing_person in missing_people:
        FulfilledMembership.objects.update_or_create(year=season_year,
                                                     person=missing_person,
                                                     defaults={
                                                         'fulfilled_membership': False,
                                                         'missing_membership_money': 0
                                                     })

    # Check Brigades
    mems = FulfilledBrigade.objects.filter(year=season_year, person__user__is_active=True)
    people_in_mem = [a.person for a in mems]
    missing_people = set(Person.objects.filter(user__is_active=True)).difference(people_in_mem)
    for missing_person in missing_people:
        FulfilledBrigade.objects.update_or_create(person=missing_person,
                                                  year=season_year,
                                                  defaults={
                                                      'fulfilled_brigade': False,
                                                      'missing_brigade_hours': 0,
                                                      'missing_brigade_money': 0})

    fulfilled_memberships = FulfilledMembership.objects \
        .filter(year=season_year, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')
    fulfilled_brigade = FulfilledBrigade.objects \
        .filter(year=season_year, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')
    fulfilled_brigade_prev = FulfilledBrigade.objects \
        .filter(year=season_year - 1, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')

    years = FulfilledMembership.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    if len(fulfilled_memberships) != len(fulfilled_brigade):
        # find missing:
        brigade_set = set([a[0] for a in fulfilled_brigade.values_list('person')])
        membership_set = set([a[0] for a in fulfilled_memberships.values_list('person')])

        for missing_person in list((membership_set - brigade_set).union(brigade_set - membership_set)):
            # print(missing_person)
            Person.objects.get(pk=missing_person).update_fees(date(season_year, 10, 1), request)

    return render(request,
                  'main/treasurer.html',
                  {"data": zip(fulfilled_memberships, fulfilled_brigade, fulfilled_brigade_prev),
                   'season_year': season_year,
                   'years': years,
                   'form': form})


@login_required
@user_passes_test(is_treasurer)
def sinners(request, season_year):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        payment = form.save(commit=False)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = PaymentForm()

    years = FulfilledMembership.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    fulfilled_brigade, fulfilled_memberships = get_unfulfilled_lists(season_year)

    return render(request,
                  'main/sinners.html',
                  {"data": zip(fulfilled_memberships, fulfilled_brigade),
                   'season_year': season_year,
                   'years': years,
                   'form': form})


@login_required
@user_passes_test(is_brigade_role)
def brigades(request, season_year=None):
    if season_year is None:
        season_year = get_season_year(date.today())
    fulfilled_brigade = (FulfilledBrigade.objects.filter(Q(year=season_year),
                                                         Q(person__user__is_active=True),
                                                         Q(person__status=MemberStatus.Member) | Q(
                                                             person__status=MemberStatus.Escaping)).select_related(
        'person')
                         .order_by('person__last_name', 'person__first_name'))

    years = FulfilledBrigade.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    return render(request,
                  'main/brigades.html',
                  {'data': fulfilled_brigade,
                   'season_year': season_year,
                   'years': years})


@login_required
def user_info(request):
    person = get_current_person(request)
    if person.is_aspirant:
        return redirect("main:aspirant_info")
    try:
        last_examination = MedicalExamination.objects.filter(person=person, rejected=False).latest('examination_until')
    except MedicalExamination.DoesNotExist:
        last_examination = None
    fulfilled_membership_this_year = person.did_user_pay_membership(year=date.today().year)
    fulfilled_membership_prev_year = person.did_user_pay_membership(year=date.today().year - 1)

    season_year = get_season_year(date.today())
    fulfilled_brigade_this_year = person.did_user_pay_brigade(season_year=season_year)
    fulfilled_brigade_prev_year = person.did_user_pay_brigade(season_year=season_year - 1)
    fulfilled_brigade_prev2_year = person.did_user_pay_brigade(season_year=season_year - 2)

    brigades_to_verify = Brigade.objects.filter(person=person,
                                                verified=False)
    brigade_hours_to_verify = sum([b.hours for b in brigades_to_verify])

    my_registrations = Registration.objects.filter(person=person,
                                                   competition__signing_from__lte=date.today(),
                                                   competition__event_date__gte=date.today())
    registration_removable = [date.today() >= r.competition.signing_from and date.today() <= r.competition.signing_until
                              for r in my_registrations]

    return render(request=request,
                  template_name="main/user_info.html",
                  context={"person": person,
                           "season_year": season_year,
                           "current_year": date.today().year,
                           "examination": last_examination,

app/main/templates/main/aspirants.html
{% extends "main/header.html" %}
{% load extra_tags %}
{% load admin_urls %}
{% load i18n %}
{% load bootstrap_icons %}

{% block content %}

<h2>{% trans "List of aspirants for" %}
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {{ current_manager }}
        </button>
        <ul class="dropdown-menu">
            {% for man in managers %}
            <li><a class="dropdown-item" href="{% url 'main:list_aspirants' man.pk %}" {% if man == current_manager %} selected="selected" {% endif %} >{{ man }}</a></li>
            {% endfor %}
        </ul>
    </div>
</h2>

<a class="btn btn-primary" href="{% url 'main:add_aspirant' %}">{% trans "Add New Aspirant" %}</a>
<input class="form-control" id="myInput" type="text" placeholder="Search..">

<table class="table table-striped table-hover" style="white-space:nowrap;" id="wideTable">
    <thead>
    <tr>
        <th>#</th>
        <th>{% trans "Person" %}</th>
        <th>{% trans "Phone no" %}</th>
        <th>{% trans "Email" %}</th>
        <th>{% trans "Temp Reg" %}</th>
        <th>{% trans "Small Reg" %}</th>
        <th>{% trans "Big Reg" %}</th>
        <th>{% trans "GDPR" %}</th>
        <th>{% trans "Info signed" %}</th>
        <th style="max-width:150px">{% trans "MF" %}</th>
        <th style="max-width:200px">{% trans "ME" %}</th>
        <th>{% trans "Photo 2 pcs" %}</th>
        <th>{% trans "Aspirant since" %}</th>
        <th>{% trans "Notes" %}</th>
        <th>{% trans "Edit" %}</th>
        <th>{% trans "Action" %}</th>
    </tr>
    </thead>
    <tbody id="searchable_table">
    {% for person, membership, eligible in data %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>

        <td>{{ person }}</td>
        <td>{{ person.phone_number }}</td>
        <td>{{ person.email }}</td>
        <td>
            {% if person.temp_registration %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_temp_registration' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {% if person.small_reg_form %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_small_registration' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {% if person.big_reg_form %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_big_registration' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {% if person.gdpr_agreed %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_gdpr' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {% if person.information_agreed %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_information_agreed' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {% if membership.fulfilled_membership %}
            &#10004;
            {% else %}
            &#10060;
                <a href="{% url 'main:send_payment_email' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'cash-coin' %}
                </a>
            {% endif %}
        </td>
        <td>
            {% if person.latest_examination > current_date %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <br/>
            {{ person.latest_examination }}
        </td>
        <td>
            {% if person.pictures2pcs %}
            &#10004;
            {% else %}
            &#10060;
            {% endif %}
            <a href="{% url 'main:toggle_aspirant_pictures2pcs' person.pk %}" class="btn btn-primary btn-sm" role="button">
                {% bs_icon 'arrow-repeat' %}
            </a>
        </td>
        <td>
            {{ person.member_since|date:'DATE_FORMAT' }}
            ({{ person.days_since_member.days }} {% trans "days" %})
        </td>
        <td>
            <form method="post" action="{% url 'main:aspirant_update_note' person.pk %}">
                {% csrf_token %}
                <textarea name="note" rows="3" cols="30">{{ person.aspirant_note|default_if_none:'' }}</textarea>
                <button type="submit" class="btn btn-primary" style="vertical-align: top;">{% trans "Save" %}</button>
            </form>
        </td>
        <td>
            <a href="/admin/auth/user/{{person.user.pk}}/change" class="btn btn-primary" role="button">{% trans "Django" %}</a>
            <a class="btn btn-primary" href="{% url 'main:edit_aspirant' person.pk %}">{% trans "HR Edit" %}</a>
        </td>
        <td>
            {% if eligible %}
                {% if person.is_czech_citizenship and person.status == 0 and not person.hosted_member%}
                    <a href="{% url 'main:accept_aspirant' pk=person.pk %} " class="btn btn-primary" role="button">{% trans "Hire" %}</a>
                {% elif person.status == 1 %}
                    <div class="badge badge-warning">{% trans "Contact IT." %}</div>
                {% elif person.hosted_member %}
                    <div class="badge badge-warning">{% trans "Hosted member - IT has no instructions." %}</div>
                {% else %}
                    <div class="badge badge-warning">{% trans "Not Czech. Contact IT." %}</div>
                {% endif %}
            {% endif %}
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

app/main/templates/main/edit_transportation_admin.html
{% extends "main/header.html" %}
{% load extra_tags %}
{% load admin_urls %}
{% load i18n %}
{% load bootstrap_icons %}

{% block content %}

<h2>{% trans "Transportation for " %} {{ competition }}</h2>
<h3>
    {% trans "Transportation Summary" %}

    {% if not transportations %}
        <button type="button" class="btn btn-danger" style="margin-left: 200px;" disabled>{% trans "Remove all cars" %}</button>
        <a class="btn btn-primary" href="{% url 'main:transportation_generate' competition.pk %}">{% trans "Generate" %}</a>
        <button type="button" class="btn btn-primary" disabled>{% trans "Publish" %}</button>
    {% else %}
        <a class="btn btn-danger" href="{% url 'main:clear_transportation' competition.pk %}" style="margin-left: 200px;" onclick="return confirm('{% trans 'Are you sure you want to clear all cars?' %}');">{% trans "Clear all cars" %}</a>
        <button type="button" class="btn btn-primary" disabled>{% trans "Generate" %}</button>
        {% if competition.transportation_done %}
            <button type="button" class="btn btn-primary" disabled>{% trans "Publish" %}</button>
        {% else %}
            <a class="btn btn-primary" href="{% url 'main:transportation_publish' competition.pk %}">{% trans "Publish" %}</a>
        {% endif %}
    {% endif %}
    {% if competition.transportation_locked %}
        <a class="btn btn-primary" href="{% url 'main:transportation_lock_toggle' competition.pk %}">{% trans "Unlock transportation" %}</a>
    {% else %}
        <a class="btn btn-warning" href="{% url 'main:transportation_lock_toggle' competition.pk %}">{% trans "Lock transportation" %}</a>
    {% endif %}
</h3>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>{% trans "Driver" %}</th>
        <th>{% trans "Phone" %}</th>
        <th>{% trans "Occupancy" %}</th>
        <th>{% trans "Passengers" %}</th>
        <th>{% trans "Note" %}</th>
        <th>{% trans "Actions" %}</th>
    </tr>
    </thead>
    <tbody>
    {% for transportation in transportations %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>
            {{ transportation.driver.get_public_name }}
            {% for registration in registrations %}
                {% if registration.person == transportation.driver %}
                    ({{ registration.length.all | join:", " }})
                {% endif %}
            {% endfor %}
        </td>
        <td>{{ transportation.driver.phone_number }}</td>
        <td>
            {% if transportation.passengers.count > transportation.available_seats %}
                {% bs_icon 'x-circle' color='red' %}
            {% endif %}
            {{ transportation.passengers.count }} / {{ transportation.available_seats }}
        </td>
        <td>
            {% for passenger in transportation.passengers.all %}
                {{ passenger.get_public_name }}
                {% for registration in registrations %}
                    {% if registration.person == passenger %}
                        ({{ registration.length.all | join:", " }})
                    {% endif %}
                {% endfor %}
                {% if not forloop.last %}<br>{% endif %}
            {% endfor %}
        </td>
        <td>
            <form method="post" action="{% url 'main:update_note' transportation.pk %}">
                {% csrf_token %}
                <textarea name="note" rows="3" cols="20">{{ transportation.note }}</textarea>
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            </form>
        </td>
        <td>
            <a class="btn btn-danger" href="{% url 'main:transportation_remove_driver' transportation.pk %}" onclick="return confirm('{% trans 'Are you sure you want to remove this car?' %}');">{% trans "Remove car" %}</a>
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    {% trans "Set Seats" %}
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 0 %}">{{ 0 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 1 %}">{{ 1 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 2 %}">{{ 2 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 3 %}">{{ 3 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 4 %}">{{ 4 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 5 %}">{{ 5 }}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'main:set_available_seats' transportation.pk 6 %}">{{ 6 }}</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<h3>{% trans "Attendees" %}</h3>
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>{% trans "Person" %}</th>
        <th>{% trans "Phone" %}</th>
        <th>{% trans "Length" %}</th>
        <th>{% trans "Preferred Transport" %}</th>
        <th>{% trans "Preferred Driver" %}</th>
        <th>{% trans "Preferred Passengers" %}</th>
        <th>{% trans "Note" %}</th>
        <th>{% trans "Action" %}</th>
        <th>{% trans "Driver" %}</th>
    </tr>
    </thead>
    <tbody>
    {% for registration in registrations %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>
            {% if registration.person.id in drivers or registration.person.id in passengers or registration.transport == 0%}
                {% bs_icon 'check-circle' color='green' %}
            {% else %}
                {% bs_icon 'x-circle' color='red' %}
            {% endif %}
            {{ registration.person.get_public_name }}
        </td>
        <td>{{ registration.person.phone_number }}</td>
        <td {% if registration.championship_course %} style="font-weight: bold;"{% endif %}>
            {{ registration.length.all | join:", " }}{% if registration.championship_course %} ({% trans 'CSC' %}) {% endif %}
        </td>
        <td>{{ registration.get_transport_pretty }}</td>
        <td>{{ registration.preferred_driver.get_public_name|default:"" }}</td>
        <td>
            {% for passenger in registration.preferred_passengers.all %}
                {{ passenger.get_public_name }}{% if not forloop.last %},<br>{% endif %}
            {% endfor %}
        </td>
        <td>{{ registration.note }}</td>
        <td> <a class="btn btn-primary" href="{% url 'main:transportation_create_driver' registration.pk %}">{% trans "Set as driver" %}</a></td>
        <td>
             <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">{% trans "Select driver" %}</button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'main:transportation_remove_passenger' registration.pk %}">{% trans "Remove" %}</a>
                        </li>
                        {% for transportation in transportations %}
                        {% if registration.person.id != transportation.driver.id %}
                            <li>
                                <a class="dropdown-item" href="{% url 'main:transportation_append_passenger' transportation.pk registration.pk %}">{{ transportation.driver.get_public_name }}</a>
                            </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
             </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}