app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('', include('main.urls')),
  path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy, re_path

from . import views
from .views import ResetPasswordView

# from rest_framework import routers


app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("user_info/", views.user_info, name="user_info"),
    path("aspirant_info/", views.aspirant_info, name="aspirant_info"),
    path("competitions/", views.list_competitions, name="list_competitions"),
    path("competition/<int:id>", views.list_attendees, name="list_attendees"),
    path("competition_public/<int:id>", views.list_attendees_public, name="list_attendees_public"),
    path("edit_transportation_admin/<int:id>", views.edit_transportation_admin, name="edit_transportation_admin"),
    path("transportation_publish/<int:id>", views.transportation_publish, name="transportation_publish"),
    path("transportation_generate/<int:id>", views.transportation_generate, name="transportation_generate"),
    path("transportation_lock_toggle/<int:id>", views.transportation_lock_toggle, name="transportation_lock_toggle"),
    path("transportation_remove_driver/<int:id>", views.transportation_remove_driver, name="transportation_remove_driver"),
    path("transportation_remove_passenger/<int:registration_id>", views.transportation_remove_passenger, name="transportation_remove_passenger"),
    path("clear_transportation/<int:id>", views.clear_transportation, name="clear_transportation"),
    path("transportation_create_driver/<int:id>", views.transportation_create_driver, name="transportation_create_driver"),
    path("transportation_append_passenger/<int:transport_id>/<int:registration_id>", views.transportation_append_passenger, name="transportation_append_passenger"),
    path('set_available_seats/<int:transportation_id>/<int:seats>/', views.set_available_seats, name='set_available_seats'),
    path('update_note/<int:pk>/', views.update_note, name='update_note'),
    path("transportation_public/<int:id>", views.transportation_public, name="transportation_public"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("hr/", views.list_members, name="list_members"),
    path("aspirants/<int:person_id>", views.list_aspirants, name="list_aspirants"),
    path("aspirants/add", views.add_aspirant, name="add_aspirant"),
    path("aspirants/edit/<int:pk>", views.edit_aspirant, name="edit_aspirant"),
    path("aspirants/accept/<int:pk>", views.accept_aspirant, name="accept_aspirant"),
    path("aspirants/edit_note/<int:pk>", views.aspirant_update_note, name="aspirant_update_note"),
    path("medical_exams/", views.medical_exams, name="medical_exams"),
    path("medical_exam/verify/<int:exam_id>/", views.verify_exam, name="verify_exam"),
    path("medical_exams_all/", views.medical_exams_all, name="medical_exams_all"),
    path("medical_exams_history/<int:person_id>", views.medical_exams_history, name="medical_exams_history"),
    path("brigade/verify/<int:brigade_id>/", views.verify_brigade, name="verify_brigade"),
    path("treasurer/<int:season_year>", views.treasurer, name="treasurer"),
    path("sinners/<int:season_year>", views.sinners, name="sinners"),
    path("brigades/<int:season_year>", views.brigades, name="brigades"),
    path("brigade_requests/", views.brigade_requests, name="brigade_requests"),
    path("brigade_history/<int:person_id>", views.brigade_history, name="brigade_history"),
    path("add_brigade/", views.add_brigade, name="add_brigade"),
    path("register/", views.register, name="register"),
    path("register_to/<int:id>", views.register_to, name="register_to"),
    path("edit_registration/<int:registration_id>", views.edit_registration, name="edit_registration"),
    path("unregister/<int:id>", views.unregister, name="unregister"),
    path("upload_new_exam_file/", views.upload_examination, name="upload_exam_file"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/competitions', views.api_competitions, name='api_competitions'),
    path('api/registrations/<int:iscsps_id>', views.api_registrations, name='api_registrations'),
    path('api/examinations', views.api_examinations, name='api_examinations'),
    path('api/add_new_member_cus/<int:pk>', views.add_new_member_cus, name='add_new_member_cus'),
    path('api/list_new_members', views.list_new_members, name='list_new_members'),
    re_path(
        r'^payment_details/(?P<fee_type>[^/]+)/(?P<year>\d+)/(?P<amount>\d+)(?:/(?P<optional_text>[^/]+))?/$',
        views.payment_details, name='payment_details'),
    path("payment_history/<int:person_id>", views.payment_history, name='payment_history'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='main/users/password_reset_confirm.html',
                                                     success_url=reverse_lazy("main:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'),
         name='password_reset_complete'),
    # path to toggle copaid for each competition
    path('toggle_co_paid/<int:competition_id>/<int:pk>/', views.toggle_co_paid, name='toggle_co_paid'),
    path('toggle_aspirant_temp_registration/<int:person_id>/', views.toggle_aspirant_temp_registration, name='toggle_aspirant_temp_registration'),
    path('toggle_aspirant_big_registration/<int:person_id>/', views.toggle_aspirant_big_registration,
         name='toggle_aspirant_big_registration'),
    path('toggle_aspirant_small_registration/<int:person_id>/', views.toggle_aspirant_small_registration,
         name='toggle_aspirant_small_registration'),
    path('toggle_aspirant_gdpr/<int:person_id>/', views.toggle_aspirant_gdpr,
         name='toggle_aspirant_gdpr'),
    path('toggle_aspirant_information_agreed/<int:person_id>/', views.toggle_aspirant_information_agreed,
         name='toggle_aspirant_information_agreed'),
    path('toggle_aspirant_pictures2pcs/<int:person_id>/', views.toggle_aspirant_pictures2pcs,
         name='toggle_aspirant_pictures2pcs'),
    path('send_payment_email/<int:person_id>/', views.send_payment_email, name='send_payment_email'),
]

app/main/views.py
import csv
import json
import re
import ssl
import urllib
import io
from datetime import date, datetime, timedelta
from urllib.error import URLError
from urllib.request import urlopen

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.db.models import Max, Q, ExpressionWrapper, F, fields
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.http import require_POST

from .utils import update_user_medical_examination_on_IS, add_new_member_to_CSPS, add_new_member_to_CUS, \
    get_unfulfilled_lists, remove_atendee_from_transportation, apply_for_competition, delete_competition_application
from .forms import RegistrationForm, ExaminationForm, BrigadeForm, PaymentForm, MedicalExaminationRejectionForm, \
    AspirantForm
from .models import Competition, Person, MedicalExamination, Brigade, Payment, Registration, FulfilledMembership, \
    FulfilledBrigade, ChampionshipCourseRule, MemberStatus, Transport
from .utils import get_season_year


def is_treasurer(user):
    return user.groups.filter(name='Treasurer Role').exists()


def is_hr(user):
    return user.groups.filter(name='HR role').exists()


def is_competition_manager(user):
    return user.groups.filter(name='Competition Manager Role').exists()


def is_medic(user):
    return user.groups.filter(name='Medical Examination Role').exists()


def is_brigade_role(user):
    return user.groups.filter(name='Brigade Manager').exists()


def homepage(request):
    return render(request=request,
                  template_name="main/home.html",
                  context={"competitions": Competition.objects.all})


transports = (
    ("", _('---------')),  # default choice
    (0, _('Individual')),
    (1, _('I need a ride')),
    (2, _('I drive (1 spare pl.)')),
    (3, _('I drive (2 spare pl.)')),
    (4, _('I drive (3 spare pl.)')),
    (5, _('I drive (4 spare pl.)')),
    (6, _('I drive (5 spare pl.)')),
    (7, _('I drive (6 spare pl.)')),
)


@login_required
def update_membership_payments(person: Person, current_date: date, request=None):
    """
    BRIGADE:
    Given year, check payments between 1.7.YEAR-1 to 1.7.YEAR
    """
    person.update_fees(current_date, request)


@login_required
@user_passes_test(is_treasurer)
def treasurer(request, season_year):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        payment = form.save(commit=False)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = PaymentForm()

    # check, if FulfilledMembership has missing some people for season_year. If so, recreate them
    # Check Memberships
    mems = FulfilledMembership.objects.filter(year=season_year, person__user__is_active=True)
    people_in_mem = [a.person for a in mems]
    missing_people = set(Person.objects.filter(user__is_active=True)).difference(people_in_mem)
    for missing_person in missing_people:
        FulfilledMembership.objects.update_or_create(year=season_year,
                                                     person=missing_person,
                                                     defaults={
                                                         'fulfilled_membership': False,
                                                         'missing_membership_money': 0
                                                     })

    # Check Brigades
    mems = FulfilledBrigade.objects.filter(year=season_year, person__user__is_active=True)
    people_in_mem = [a.person for a in mems]
    missing_people = set(Person.objects.filter(user__is_active=True)).difference(people_in_mem)
    for missing_person in missing_people:
        FulfilledBrigade.objects.update_or_create(person=missing_person,
                                                  year=season_year,
                                                  defaults={
                                                      'fulfilled_brigade': False,
                                                      'missing_brigade_hours': 0,
                                                      'missing_brigade_money': 0})

    fulfilled_memberships = FulfilledMembership.objects \
        .filter(year=season_year, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')
    fulfilled_brigade = FulfilledBrigade.objects \
        .filter(year=season_year, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')
    fulfilled_brigade_prev = FulfilledBrigade.objects \
        .filter(year=season_year - 1, person__user__is_active=True) \
        .select_related('person').order_by('person__last_name', 'person__first_name', 'person__birth_date')

    years = FulfilledMembership.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    if len(fulfilled_memberships) != len(fulfilled_brigade):
        # find missing:
        brigade_set = set([a[0] for a in fulfilled_brigade.values_list('person')])
        membership_set = set([a[0] for a in fulfilled_memberships.values_list('person')])

        for missing_person in list((membership_set - brigade_set).union(brigade_set - membership_set)):
            # print(missing_person)
            Person.objects.get(pk=missing_person).update_fees(date(season_year, 10, 1), request)

    return render(request,
                  'main/treasurer.html',
                  {"data": zip(fulfilled_memberships, fulfilled_brigade, fulfilled_brigade_prev),
                   'season_year': season_year,
                   'years': years,
                   'form': form})


@login_required
@user_passes_test(is_treasurer)
def sinners(request, season_year):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        payment = form.save(commit=False)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = PaymentForm()

    years = FulfilledMembership.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    fulfilled_brigade, fulfilled_memberships = get_unfulfilled_lists(season_year)

    return render(request,
                  'main/sinners.html',
                  {"data": zip(fulfilled_memberships, fulfilled_brigade),
                   'season_year': season_year,
                   'years': years,
                   'form': form})


@login_required
@user_passes_test(is_brigade_role)
def brigades(request, season_year=None):
    if season_year is None:
        season_year = get_season_year(date.today())
    fulfilled_brigade = (FulfilledBrigade.objects.filter(Q(year=season_year),
                                                         Q(person__user__is_active=True),
                                                         Q(person__status=MemberStatus.Member) | Q(
                                                             person__status=MemberStatus.Escaping)).select_related(
        'person')
                         .order_by('person__last_name', 'person__first_name'))

    years = FulfilledBrigade.objects.order_by('-year').values_list('year').distinct()
    years = [a[0] for a in years]

    return render(request,
                  'main/brigades.html',
                  {'data': fulfilled_brigade,
                   'season_year': season_year,
                   'years': years})


@login_required
def user_info(request):
    person = get_current_person(request)
    if person.is_aspirant:
        return redirect("main:aspirant_info")
    try:
        last_examination = MedicalExamination.objects.filter(person=person, rejected=False).latest('examination_until')
    except MedicalExamination.DoesNotExist:
        last_examination = None
    fulfilled_membership_this_year = person.did_user_pay_membership(year=date.today().year)
    fulfilled_membership_prev_year = person.did_user_pay_membership(year=date.today().year - 1)

    season_year = get_season_year(date.today())
    fulfilled_brigade_this_year = person.did_user_pay_brigade(season_year=season_year)
    fulfilled_brigade_prev_year = person.did_user_pay_brigade(season_year=season_year - 1)
    fulfilled_brigade_prev2_year = person.did_user_pay_brigade(season_year=season_year - 2)

    brigades_to_verify = Brigade.objects.filter(person=person,
                                                verified=False)
    brigade_hours_to_verify = sum([b.hours for b in brigades_to_verify])

    my_registrations = Registration.objects.filter(person=person,
                                                   competition__signing_from__lte=date.today(),
                                                   competition__event_date__gte=date.today())
    registration_removable = [date.today() >= r.competition.signing_from and date.today() <= r.competition.signing_until
                              for r in my_registrations]

    return render(request=request,
                  template_name="main/user_info.html",
                  context={"person": person,
                           "season_year": season_year,
                           "current_year": date.today().year,
                           "examination": last_examination,

app/main/templates/main/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "success" %}
            <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000})</script>
        {% elif message.tags == "info" %}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000})</script>
        {% elif message.tags == "warning" %}
            <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000})</script>
        {% elif message.tags == "error" %}
            <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000})</script>
        {% endif %}
    {% endfor %}
{% endif %}

app/main/templates/main/includes/navbar.html
{% load static %}
{% load bootstrap5 %}
{% load i18n %}
{% load extra_tags %}
{% now "Y"  as current_year %}
{% current_brigade_season as brigade_season %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <img src="{% static 'favicon.png' %}"/>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-light" aria-current="page" href="/user_info">{% trans "Profile" %}</a>
                </li>
                {% if person.is_competition_manager %}
                <li class="nav-item">
                    <a class="btn btn-light" href="/competitions">{% trans "Competitions" %}</a>
                </li>
                {% endif %}
                {% if person.is_medical_exam_manager %}
                <li class="nav-item">
                    <a class="btn btn-light" href="/medical_exams">{% trans "Medical Examinations to confirm" %}</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light" href="/medical_exams_all">{% trans "Medical Examinations" %}</a>
                </li>
                {% endif %}
                {% if person.is_treasurer %}
                <li class="nav-item">
                    <a class="btn btn-light" href="{% url 'main:treasurer' current_year %}">{% trans "Treasurer" %}</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light" href="{% url 'main:sinners' brigade_season %}">{% trans "Sinners" %}</a>
                </li>
                {% endif %}
                {% if person.is_brigade_manager %}
                <li class="nav-item">
                    <a class="btn btn-light" href="{% url 'main:brigades' brigade_season %}">{% trans "Brigades" %}</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light" href="/brigade_requests">{% trans "Brigades to confirm" %}</a>
                </li>
                {% endif %}
                {% if person.is_human_resource_manager %}
                <li class="nav-item">
                    <a class="btn btn-light" href="/hr">{%trans "HR" %}</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light" href="{% url 'main:list_aspirants' person.id %}">{% trans "Aspirants" %}</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                </li>
                {% endif %}

                <li class="nav-dropdown">
                    <form action="/i18n/setlang/" method="POST" id="lang">
                        {% csrf_token %}
                        <select name="language" onchange="this.form.submit();" class="custom-select">
                            {% for lang in LANGUAGES %}
                                <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected="selected" {% endif %}> {{ lang.1 }}
                                </option>
                            {% endfor %}
                        </select>
                        <noscript><input type="submit"></noscript>
                    </form>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="btn btn-secondary" href="/logout">{% trans "Logout" %}</a>
                    {% else %}
                    <a class="nav-link" href="/login">{% trans "Login" %}</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>