app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('', include('main.urls')),
  path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy, re_path

from . import views
from .views import ResetPasswordView

# from rest_framework import routers


app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("user_info/", views.user_info, name="user_info"),
    path("aspirant_info/", views.aspirant_info, name="aspirant_info"),
    path("competitions/", views.list_competitions, name="list_competitions"),
    path("competition/<int:id>", views.list_attendees, name="list_attendees"),
    path("competition_public/<int:id>", views.list_attendees_public, name="list_attendees_public"),
    path("edit_transportation_admin/<int:id>", views.edit_transportation_admin, name="edit_transportation_admin"),
    path("transportation_publish/<int:id>", views.transportation_publish, name="transportation_publish"),
    path("transportation_generate/<int:id>", views.transportation_generate, name="transportation_generate"),
    path("transportation_lock_toggle/<int:id>", views.transportation_lock_toggle, name="transportation_lock_toggle"),
    path("transportation_remove_driver/<int:id>", views.transportation_remove_driver, name="transportation_remove_driver"),
    path("transportation_remove_passenger/<int:registration_id>", views.transportation_remove_passenger, name="transportation_remove_passenger"),
    path("clear_transportation/<int:id>", views.clear_transportation, name="clear_transportation"),
    path("transportation_create_driver/<int:id>", views.transportation_create_driver, name="transportation_create_driver"),
    path("transportation_append_passenger/<int:transport_id>/<int:registration_id>", views.transportation_append_passenger, name="transportation_append_passenger"),
    path('set_available_seats/<int:transportation_id>/<int:seats>/', views.set_available_seats, name='set_available_seats'),
    path('update_note/<int:pk>/', views.update_note, name='update_note'),
    path("transportation_public/<int:id>", views.transportation_public, name="transportation_public"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("hr/", views.list_members, name="list_members"),
    path("aspirants/<int:person_id>", views.list_aspirants, name="list_aspirants"),
    path("aspirants/add", views.add_aspirant, name="add_aspirant"),
    path("aspirants/edit/<int:pk>", views.edit_aspirant, name="edit_aspirant"),
    path("aspirants/accept/<int:pk>", views.accept_aspirant, name="accept_aspirant"),
    path("aspirants/edit_note/<int:pk>", views.aspirant_update_note, name="aspirant_update_note"),
    path("medical_exams/", views.medical_exams, name="medical_exams"),
    path("medical_exam/verify/<int:exam_id>/", views.verify_exam, name="verify_exam"),
    path("medical_exams_all/", views.medical_exams_all, name="medical_exams_all"),
    path("medical_exams_history/<int:person_id>", views.medical_exams_history, name="medical_exams_history"),
    path("brigade/verify/<int:brigade_id>/", views.verify_brigade, name="verify_brigade"),
    path("treasurer/<int:season_year>", views.treasurer, name="treasurer"),
    path("sinners/<int:season_year>", views.sinners, name="sinners"),
    path("brigades/<int:season_year>", views.brigades, name="brigades"),
    path("brigade_requests/", views.brigade_requests, name="brigade_requests"),
    path("brigade_history/<int:person_id>", views.brigade_history, name="brigade_history"),
    path("add_brigade/", views.add_brigade, name="add_brigade"),
    path("register/", views.register, name="register"),
    path("register_to/<int:id>", views.register_to, name="register_to"),
    path("edit_registration/<int:registration_id>", views.edit_registration, name="edit_registration"),
    path("unregister/<int:id>", views.unregister, name="unregister"),
    path("upload_new_exam_file/", views.upload_examination, name="upload_exam_file"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/competitions', views.api_competitions, name='api_competitions'),
    path('api/registrations/<int:iscsps_id>', views.api_registrations, name='api_registrations'),
    path('api/examinations', views.api_examinations, name='api_examinations'),
    path('api/add_new_member_cus/<int:pk>', views.add_new_member_cus, name='add_new_member_cus'),
    path('api/list_new_members', views.list_new_members, name='list_new_members'),
    re_path(
        r'^payment_details/(?P<fee_type>[^/]+)/(?P<year>\d+)/(?P<amount>\d+)(?:/(?P<optional_text>[^/]+))?/$',
        views.payment_details, name='payment_details'),
    path("payment_history/<int:person_id>", views.payment_history, name='payment_history'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='main/users/password_reset_confirm.html',
                                                     success_url=reverse_lazy("main:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'),
         name='password_reset_complete'),
    # path to toggle copaid for each competition
    path('toggle_co_paid/<int:competition_id>/<int:pk>/', views.toggle_co_paid, name='toggle_co_paid'),
    path('toggle_aspirant_temp_registration/<int:person_id>/', views.toggle_aspirant_temp_registration, name='toggle_aspirant_temp_registration'),
    path('toggle_aspirant_big_registration/<int:person_id>/', views.toggle_aspirant_big_registration,
         name='toggle_aspirant_big_registration'),
    path('toggle_aspirant_small_registration/<int:person_id>/', views.toggle_aspirant_small_registration,
         name='toggle_aspirant_small_registration'),
    path('toggle_aspirant_gdpr/<int:person_id>/', views.toggle_aspirant_gdpr,
         name='toggle_aspirant_gdpr'),
    path('toggle_aspirant_information_agreed/<int:person_id>/', views.toggle_aspirant_information_agreed,
         name='toggle_aspirant_information_agreed'),
    path('toggle_aspirant_pictures2pcs/<int:person_id>/', views.toggle_aspirant_pictures2pcs,
         name='toggle_aspirant_pictures2pcs'),
    path('send_payment_email/<int:person_id>/', views.send_payment_email, name='send_payment_email'),
]

app/main/models.py
from datetime import date, datetime
from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.translation import gettext as _
from simple_history.models import HistoricalRecords
from .utils import get_season_year, get_season_end_year


# Create your models here.
class AgeTypes(models.IntegerChoices):
    junior = 0, _('junior')
    regular = 1, _('regular')
    senior = 2, _('senior')
    elder = 3, _('elder')

class MemberStatus(models.IntegerChoices):
    Aspirant = 0, _('Aspirant')
    Accepting = 1, _('Member acceptation in progress')
    Member = 2, _('Member')
    Escaping = 3, _('Escaping member')
    Exmember = 4, _('Exmember')



class SwimmerCategory(models.IntegerChoices):
    young_male = 0, _('Young Male')
    young_female = 1, _('Young Female')
    male_a = 2, _('Male A')
    female_a = 3, _('Female A')
    male_b = 4, _('Male B')
    female_b = 5, _('Female B')
    male_masters_a = 6, _('Male Masters A')
    female_masters_a = 7, _('Female Masters A')
    male_masters_b = 8, _('Male Masters B')
    female_masters_b = 9, _('Female Masters B')
    male_masters_c = 10, _('Male Masters C')
    female_masters_c = 11, _('Female Masters C')
    male_masters_d = 12, _('Male Masters D')
    female_masters_d = 13, _('Female Masters D')
    male_masters_e = 14, _('Male Masters E')
    female_masters_e = 15, _('Female Masters E')


def get_swimmercategory(desired: int):
    choices = [c[1] for c in SwimmerCategory.choices if c[0] == desired]
    return choices[0]


def get_swimmerage_type(desired: int):
    choices = [c[1] for c in AgeTypes.choices if c[0] == desired]
    return choices[0]


class CompetitionVenue(models.Model):
    is_homeplace = models.BooleanField(_('Is homeplace'), default=False)
    location = models.CharField(_('Location'), max_length=512, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.location


class CompetitionLength(models.Model):
    length = models.DecimalField(_('Length'), decimal_places=1, max_digits=5)
    history = HistoricalRecords()

    def __str__(self):
        leng = int(self.length) if self.length % 1 == 0 else self.length
        if self.length < 50:
            return str(leng) + ' km'
        else:
            return str(leng) + ' m'


class ChampionshipCourseRule(models.Model):
    temp_under4 = models.BooleanField(_('Water temperature under 4 deg'), default=True)
    swimmercategory = models.IntegerField(_('Swimmer category'), choices=SwimmerCategory.choices, default=SwimmerCategory.male_a)
    length = models.ForeignKey(CompetitionLength, on_delete=models.CASCADE, verbose_name=_('Course length'))
    history = HistoricalRecords()


class Competition(models.Model):
    event_date = models.DateField(_('Date'), default=date.today)
    event_venue = models.ForeignKey(CompetitionVenue, on_delete=models.CASCADE, verbose_name=_('Venue'))
    name = models.CharField(_('Name'), max_length=200, default='')
    lengths = models.ManyToManyField(CompetitionLength, verbose_name=_('Lengths'))
    signing_from = models.DateField(_('Sign in from'), default=date.today)
    signing_until = models.DateField(_('Sign in until'), default=date.today)
    expected_temp = models.CharField(_('Expected temperature'), max_length=3,
                                     choices=models.TextChoices('Temperature', '4- 4+ 8+').choices,
                                     default='4-')
    propositions = models.CharField(_('Propositions'), max_length=256, blank=True, null=True)
    iscsps_id = models.IntegerField('IS-CSPS ID')
    is_winter_competition = models.BooleanField(_('Is winter competition'), default=False)
    is_championship_venue = models.BooleanField(_('Is championship'), default=False)
    note = models.CharField(_('Note'), max_length=500, blank=True, null=True)
    copayment = models.IntegerField(_('Copayment'), default=0)
    transportation_payment = models.IntegerField(_('Transportation payment'), default=0)
    transportation_done = models.BooleanField(_('Transportation done'), default=False)
    transportation_locked = models.BooleanField(_('Transportation locked'), default=False)
    history = HistoricalRecords()

    def __str__(self):
        return ' - '.join([str(self.event_venue), str(self.event_date.strftime('%d.%m.%Y'))])


class Person(models.Model):
    class Levels(models.IntegerChoices):
        O = 0, _('0')
        I = 1, _('I')
        II = 2, _('II')
        III = 3, _('III')
        M = 4, _('M')

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name=_('User'))
    first_name = models.CharField(_('First name'), max_length=25, default='')
    last_name = models.CharField(_('Last name'), max_length=25, default='')
    email = models.EmailField(max_length=100, default="", blank=True, null=True)
    birth_date = models.DateField(_('Birth date'), default=date.today, help_text="YYYY-MM-DD")
    RC = models.CharField(_('RC'), max_length=18, blank=True, null=True, help_text="YYMMDD/XXXX")
    sex = models.CharField(_('Sex'), max_length=10, choices=models.TextChoices('Sex', 'Male Female').choices,
                           default='Male')

    # contact info
    address = models.CharField(_('Address'), max_length=200, blank=True, null=True)
    phone_number = models.CharField(_('Phone number'), max_length=17, blank=True, null=True)

    # swimming info
    is_honorable = models.BooleanField(_('Is honorable'), default=False)
    member_since = models.DateField(_('Member since'), default=date.today)
    pass_id = models.IntegerField(_('Card ID'), blank=True, null=True)
    points_id = models.IntegerField(_('ID on bodovani.zimni-plavani.info'), default=0)
    iscsps_id = models.IntegerField(_('ID on IS CSPS'), default=0)
    person_allowed_to_register = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True,
                                                   verbose_name=_('Person allowed to register'))
    level_now = models.IntegerField(_('Swimming level actual'), choices=Levels.choices, default=Levels.O)
    level_last_year = models.IntegerField(_('Swimming level previous'), choices=Levels.choices, default=Levels.O)
    hosted_member = models.BooleanField(_('Hosted member'), default=False)
    # aspirant info
    status = models.IntegerField(_('Member status'), choices=MemberStatus.choices, default=MemberStatus.Member)
    temp_registration = models.BooleanField(_('Temporary Registration'), default=False)
    small_reg_form = models.BooleanField(_('Small registration form'), default=False)
    big_reg_form = models.BooleanField(_('Big registration form'), default=False)
    gdpr_agreed = models.BooleanField(_('GDPR Agreed'), default=False)
    information_agreed = models.BooleanField(_('Club Information Signed'), default=False)
    pictures2pcs = models.BooleanField(_('Pictures 2 pcs'), default=False)
    aspirant_note = models.CharField(_('Notes'), max_length=500, blank=True, null=True)
    aspirant_manager = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True,
                                         related_name='Aspirants', verbose_name=_('HR Manager'))
    adr_street = models.CharField(_('Street'), max_length=100, blank=True, null=True)
    adr_home_number_popisne = models.CharField(_('House Number'), max_length=10, blank=True, null=True)
    adr_post_code = models.CharField(_('Post Code'), max_length=10, blank=True, null=True)
    adr_home_number2_orientacni = models.CharField(_('Orientation Number'), max_length=10, blank=True, null=True)
    adr_city = models.CharField(_('City'), max_length=70, blank=True, null=True)
    is_czech_citizenship = models.BooleanField(_('Czech citizenship'), default=True)
    history = HistoricalRecords()

    @property
    def is_aspirant(self):
        return self.status == MemberStatus.Aspirant or self.status == MemberStatus.Accepting

    @property
    def is_escaping(self):
        return self.status == MemberStatus.Escaping

    @property
    def is_treasurer(self):
        return self.user.groups.filter(name='Treasurer Role').exists()

    @property
    def is_competition_manager(self):
        return self.user.groups.filter(name='Competition Manager Role').exists()

    @property
    def is_brigade_manager(self):
        return self.user.groups.filter(name='Brigade Manager').exists()

    @property
    def is_human_resource_manager(self):
        return self.user.groups.filter(name='HR role').exists()

    @property
    def is_medical_exam_manager(self):
        return self.user.groups.filter(name='Medical Examination Role').exists()

    @property
    def get_level_now_pretty(self):
        return self.Levels(self.level_now).label

    @property
    def get_level_last_year_pretty(self):
        return self.Levels(self.level_last_year).label

    def get_swimmerage_type(self, from_year=None):
        if from_year is None:
            from_year = date.today().year
        if self.is_honorable:
            return AgeTypes.elder
        age = from_year - self.birth_date.year
        if age < 18:
            return AgeTypes.junior
        elif age < 70:
            return AgeTypes.regular
        elif age < 80:
            return AgeTypes.senior
        return AgeTypes.elder

    def get_swimmercategory(self):
        age = get_season_end_year(date.today()) - self.birth_date.year
        if age < 20:
            return SwimmerCategory.young_male if self.sex == "Male" else SwimmerCategory.young_female
        elif age < 30:
            return SwimmerCategory.male_a if self.sex == "Male" else SwimmerCategory.female_a
        elif age < 40:
            return SwimmerCategory.male_b if self.sex == "Male" else SwimmerCategory.female_b
        elif age < 50:

app/main/templates/main/users/password_reset.html
{% extends "main/header.html" %}
{% load extra_tags %}
{% load admin_urls %}
{% load bootstrap_icons %}
{% load i18n %}
{% block content %}

    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">{% trans "Forgot Password" %}?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"/>
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">{% trans "Submit" %}
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'main:login' %}">{% trans "Back To Login" %}</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

app/main/templates/main/users/password_reset_complete.html
{% extends "main/header.html" %}
{% load extra_tags %}
{% load admin_urls %}
{% load bootstrap_icons %}
{% load i18n %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        {% trans "Your password has been set. You may go ahead and" %} <a href="{% url 'main:login' %}">{% trans "Login Here" %}.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

app/main/templates/main/users/password_reset_confirm.html
{% extends "main/header.html" %}
{% block title %} Password Reset {% endblock title%}
{% load extra_tags %}
{% load admin_urls %}
{% load bootstrap_icons %}
{% load i18n %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">{% trans "Reset Your Password" %}</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">{% trans "New Password" %}</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">{% trans "New Password Confirmation" %}</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">{% trans "Reset Password" %}</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        {% trans "The password reset link was invalid, possibly because it has already been used." %}
                        {% trans "Please request a new password reset." %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}